services:
  # ChromaDB Vector Database
  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: intelligent_crawl4ai_chromadb
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - chromadb_data:/chroma/chroma
    ports:
      - "8000:8000"
    networks:
      - ai_network
    restart: unless-stopped

  # Redis for session management
  redis:
    image: redis:7-alpine
    container_name: intelligent_crawl4ai_redis
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_network
    restart: unless-stopped

  # PostgreSQL for persistent data storage
  postgres:
    image: postgres:15
    container_name: intelligent_crawl4ai_postgres
    environment:
      - POSTGRES_DB=intelligent_scraping
      - POSTGRES_USER=scraper_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - ai_network
    restart: unless-stopped

  # Browser Pool 1 - Primary
  browser-pool-1:
    image: browserless/chrome:latest
    container_name: intelligent_crawl4ai_browser_1
    ports:
      - "3001:3000"
    environment:
      - CONCURRENT=20
      - TOKEN=browser_token_1
      - ENABLE_DEBUGGER=false
      - MAX_CONCURRENT_SESSIONS=20
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - DEFAULT_STEALTH=true
    shm_size: 2gb
    networks:
      - ai_network
    restart: unless-stopped

  # Browser Pool 2 - Secondary
  browser-pool-2:
    image: browserless/chrome:latest
    container_name: intelligent_crawl4ai_browser_2
    ports:
      - "3002:3000"
    environment:
      - CONCURRENT=20
      - TOKEN=browser_token_2
      - ENABLE_DEBUGGER=false
      - MAX_CONCURRENT_SESSIONS=20
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - DEFAULT_STEALTH=true
    shm_size: 2gb
    networks:
      - ai_network
    restart: unless-stopped

  # 🌐 Web UI Server - Uses Local Ollama
  web-ui:
    image: python:3.11-slim
    command: >
      bash -c "apt-get update && apt-get install -y curl && pip install -r requirements.txt && python web_ui_server.py"
    container_name: intelligent_crawl4ai_web_ui
    working_dir: /app
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434  # ← Points to local Ollama
      - OLLAMA_MODEL=deepseek-coder:1.3b
      - CHROMADB_URL=http://chromadb:8000
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://scraper_user:secure_password_123@postgres:5432/intelligent_scraping
      - DATABASE_TYPE=postgresql  # Using PostgreSQL now
      - BROWSER_POOL_URLS=http://browser-pool-1:3000,http://browser-pool-2:3000
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8888
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./data:/app/data
      - ./web_ui_server.py:/app/web_ui_server.py
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - chromadb
      - redis
      - postgres
      - browser-pool-1
      - browser-pool-2
    networks:
      - ai_network
    ports:
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # ← Allows access to local Ollama
    restart: unless-stopped

  # High-Volume Worker Pool
  high-volume-workers:
    build:
      context: .
      dockerfile: docker/Dockerfile.workers
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://scraper_user:secure_password_123@postgres:5432/intelligent_scraping
      - OLLAMA_URL=http://host.docker.internal:11434  # ← Points to local Ollama
      - OLLAMA_MODEL=deepseek-coder:1.3b
      - CHROMADB_URL=http://chromadb:8000
      - BROWSER_POOL_URLS=http://browser-pool-1:3000,http://browser-pool-2:3000
      - MAX_WORKERS=50
      - MAX_CONCURRENT_PER_WORKER=10
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - high_volume_data:/app/data
    depends_on:
      - redis
      - postgres
    networks:
      - ai_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # ← Allows access to local Ollama
    deploy:
      replicas: 2
    restart: unless-stopped

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: intelligent_crawl4ai_prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - ai_network
    restart: unless-stopped

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: intelligent_crawl4ai_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - ai_network
    depends_on:
      - prometheus
    restart: unless-stopped

  # Load Balancer for Browser Pools
  nginx:
    image: nginx:alpine
    container_name: intelligent_crawl4ai_nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - browser-pool-1
      - browser-pool-2
    networks:
      - ai_network
    restart: unless-stopped

volumes:
  chromadb_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local
  high_volume_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  ai_network:
    driver: bridge
