services:
  # Minimal dev setup with hot reload
  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: intelligent_crawl4ai_chromadb
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - chromadb_data:/chroma/chroma
    ports:
      - "8000:8000"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: intelligent_crawl4ai_redis
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  browser-pool:
    image: browserless/chrome:latest
    container_name: intelligent_crawl4ai_browser
    ports:
      - "3001:3000"
    environment:
      - CONCURRENT=10
      - TOKEN=browser_token_1
      - ENABLE_DEBUGGER=false
      - MAX_CONCURRENT_SESSIONS=10
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - DEFAULT_STEALTH=true
    shm_size: 1gb
    restart: unless-stopped

  # Web UI with HOT RELOAD - no restart needed!
  web-ui:
    image: python:3.11-slim
    container_name: intelligent_crawl4ai_web_ui
    working_dir: /app
    # This command includes --reload flag for hot reloading
    command: >
      bash -c "
      apt-get update && apt-get install -y curl &&
      pip install -r requirements.txt &&
      echo 'Starting with hot reload enabled...' &&
      uvicorn web_ui_server:app --host 0.0.0.0 --port 8888 --reload --reload-dir /app"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=deepseek-coder:1.3b
      - CHROMADB_URL=http://chromadb:8000
      - REDIS_URL=redis://redis:6379
      - DATABASE_TYPE=sqlite
      - BROWSER_POOL_URLS=http://browser-pool:3000
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8888
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    volumes:
      # All your code is mounted - changes are instant!
      - ./:/app
      - /app/.git  # Exclude .git directory
      - /app/venv  # Exclude venv if present
      - /app/node_modules  # Exclude node_modules
    ports:
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - chromadb
      - redis
      - browser-pool

volumes:
  chromadb_data:
  redis_data:
