global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # AI-First Web Scraping Agent metrics
  - job_name: 'web-scraper'
    static_configs:
      - targets: ['web-scraper:8888']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

  # Ollama AI inference metrics
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 10s

  # Celery worker metrics
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-worker:8000']
    scrape_interval: 10s

  # System metrics (if node_exporter is available)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

# Alerting rules for the AI-First system
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Custom recording rules for AI-First metrics
rule_files:
  - "/etc/prometheus/rules/*.yml"
