services:
  # Grafana with dashboards pre-loaded
  grafana-complete:
    image: grafana/grafana:latest
    container_name: grafana_complete
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../../docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ../../docker/grafana/dashboards/crawl4ai-dashboard.json:/var/lib/grafana/dashboards/crawl4ai.json:ro
    ports:
      - "3004:3000"
    restart: unless-stopped

volumes:
  grafana_data:
    driver: local
